/**
 * ══════════════════════════════════════════════════════════════════════
 * GameSage — Base de Conocimientos: 64 HABILIDADES DE KIRBY
 * Archivo: data.js
 * ══════════════════════════════════════════════════════════════════════
 */

// DICCIONARIO DE ALIAS (Traducciones y Sinónimos)
const ALIASES = {
  "Animal": ["Animal", "Salvaje"],
  "Beetle": ["Escarabajo"],
  "Spider": ["Araña"],
  "Sword": ["	Espada"],
  "Cutter": ["Cuchilla", "Cuchillo"],
  "Hammer": ["Martillo", "Mazo"],
  "Spear": ["Lanza"],
  "Whip": ["Latigo"],
  "Archer": ["Arquero"],
  "Ranger": ["Pistolero"],
  "Throw": ["Lanzamiento", "Arrojar"],
  "Fighter": ["Luchador", "Peleador"],
  "Ninja": ["Ninja"],
  "Fire": ["Fuego"],
  "Burning": ["Llamas", "Ardiente"],
  "Ice": ["Hielo"],
  "Water": ["Agua"],
  "Bubble": ["Burbuja"],
  "Spark": ["Chispa"],
  "Beam": ["Rayo"],
  "Stone": ["Piedra", "Roca"],
  "Sand": ["Arena"],
  "Leaf": ["Hoja"],
  "Tornado": ["Tornado"],
  "UFO": ["Ovni", "UFO"],
  "Missile": ["Misil"],
  "Jet": ["Jet"],
  "Mecha": ["Meca", "Mecha"],
  "Laser": ["Laser"],
  "Mirror": ["Espejo"],
  "Ghost": ["Fantasma"],
  "Magic": ["Magia"],
  "ESP": ["Psicokinesis", "Psíquico", "ESP"],
  "Crash": ["Catapum", "Explosión"],
  "Mike": ["Micrófono", "Música"],
  "Paint": ["Pintura"],
  "Light": ["Luz"],
  "Festival": ["Festival"],
  "Cook": ["Cocinero", "Cocina"],
  "Parasol": ["Sombrilla", "Paraguas"],
  "Cleaning": ["Limpieza", "Escoba"],
  "Doctor": ["Doctor"],
  "Drill": ["Taladro"],
  "Artist": ["Artista"],
  "Yo-Yo": ["Yo-Yo"],
  "Circus": ["Circo"],
  "Bell": ["Campana"],
  "Bomb": ["Bomba"],
  "Wheel": ["Rueda"],
  "Mini": ["Mini", "Pequeño"],
  "Wing": ["Ala", "Pajaro", "Alas"],
  "Sleep": ["Dormir", "Sueño"],
  "Smash Bros": ["Smash"],
  "Poison": ["Veneno"],
  "Staff": ["Baston"],
  "Metal": ["Metal", "Hierro"],
  "Needle": ["Aguja", "Erizo"]
};

const MUTEX_GROUPS = [
  // Si Kirby está dormido, NO puede hacer absolutamente nada más
  ["dormir", "arma_fisica"],
  ["dormir", "proyectil"],
  ["dormir", "artes_marciales"],
  ["dormir", "vuelo"],
  ["dormir", "cuerpo_completo"]
];

const BASE_QUESTIONS = [
  // ── NATURALEZA DE LA HABILIDAD ──
  { id: "uso_acuatico", text: "¿Se puede usar la habilidad mientras Kirby está nadando bajo el agua?" },
  { id: "uso_unico", text: "¿Es una habilidad que Kirby pierde automáticamente tras realizar su ataque especial (o tras muy pocos usos)?" },
  { id: "cuerpo_completo", text: "¿El cuerpo de Kirby se transforma por completo? o ¿Al realizar un movimiento?" },
  { id: "arma_fisica", text: "¿Kirby empuña un arma física o herramienta en sus manos?" },
  { id: "vuelo", text: "¿Otorga alas, propulsores o cambia la forma en que Kirby vuela?" },
  { id: "inmunidad", text: "¿Tiene algun movimiento que te haga invulnerable al daño?" },
  { id: "desplazamiento", text: "¿Kirby se desplaza por el suelo de una forma única?" },

  // ── ELEMENTOS ──
  { id: "elem_fuego", text: "¿Los ataques son de fuego o quema a los enemigos?" },
  { id: "elem_hielo", text: "¿Los ataques son de hielo o puede congelar a los enemigos?" },
  { id: "elem_rayo", text: "¿Los ataques son de electricidad, rayos o plasma?" },
  { id: "elem_agua", text: "¿Los ataques o el poder se basan en agua?" },
  { id: "elem_viento", text: "¿Genera tornados o ráfagas fuertes de viento?" },
  { id: "elem_tierra", text: "¿Controla la tierra, la arena o piedras?" },
  { id: "nat_planta", text: "¿Controla hojas de árboles?" },

  // ── TIPOS DE ATAQUE / ESTILOS ──
  { id: "proyectil", text: "¿Se centra en lanzar objetos, rayos o disparar de alguna forma?" },
  { id: "corte", text: "¿La habilidad puede cortar cuerdas o deshacerse de la hierba?" },
  { id: "explosivo", text: "¿La habilidad genera grandes explosiones o utiliza bombas?" },
  { id: "artes_marciales", text: "¿Se basa en combates cuerpo a cuerpo, llaves de lucha libre o ninjutsu?" },
  { id: "musica_ruido", text: "¿Ataca utilizando el sonido, cantando o tocando instrumentos?" },
  { id: "magia_psiquico", text: "¿Usa trucos de magia, poderes mentales, o ilusiones?" },
  { id: "nat_animal", text: "¿Le da a Kirby un traje o características peludas/insectoides de un animal?" },

  // ── OBJETOS Y PROFESIONES ESPECÍFICAS ──
  { id: "sombrilla", text: "¿Usa un paraguas para atacar y flotar suavemente desde el aire?" },
  { id: "latigo", text: "¿Usa un látigo para golpear y atraer objetos inalcanzables?" },
  { id: "mazo", text: "¿Empuña un martillo gigante de madera o metal?" },
  { id: "lanza", text: "¿Usa una lanza o jabalina para pinchar y lanzar?" },
  { id: "arco_pistola", text: "¿Usa un arco con flechas o un par de pistolas?" },
  { id: "herramienta_trabajo", text: "¿Usa una escoba de limpieza o herramientas de doctor/circo?" },
  { id: "comida", text: "¿Convierte a los enemigos en comida o tiene temática de cocina?" },
  { id: "arte", text: "¿Se basa en pintar, dibujar o crear esculturas?" },
  { id: "deporte_juego", text: "¿Utiliza un yoyó, pelotas o elementos de gimnasia?" },
  { id: "tecnologia_robotica", text: "¿Kirby posee cualidades tecnologicas avanzadas?" },

  // ── MECÁNICAS DE NICHO ──
  { id: "dormir", text: "¿La habilidad es inútil para el combate y solo hace que Kirby descanse?" },
  { id: "caida_libre", text: "¿El ataque principal consiste en dejarse caer pesadamente contra el suelo (ej. Roca/Hierro)?" },
  { id: "reflejar", text: "¿Crea escudos que rebotan los proyectiles enemigos o se basa en espejos?" },
  { id: "agarre_lanza", text: "¿Tiene varias mecanicas de agarrar al enemigo y arrojarlo lejos?" },
  { id: "referencia", text: "¿La habilidad es una referencia directa a 'Super Smash Bros'?" }
];

const BASE_RULES = [
  // Animales
  { c: ["nat_animal","artes_marciales", "corte", "no_vuelo", "no_referencia"], t: "Animal" },
  { c: ["nat_animal", "artes_marciales", "corte", "vuelo", "no_referencia"], t: "Beetle" },
  { c: ["nat_animal", "artes_marciales", "agarre_lanza", "no_corte", "no_vuelo", "no_referencia"], t: "Spider" },
  // Armas
  { c: ["arma_fisica", "corte", "uso_acuatico", "no_proyectil", "no_vuelo"], t: "Sword" },
  { c: ["arma_fisica", "corte", "proyectil", "no_uso_acuatico", "no_inmunidad", "no_vuelo"], t: "Cutter" },
  { c: ["arma_fisica", "mazo", "uso_acuatico", "referencia", "no_proyectil", "no_vuelo"], t: "Hammer" },
  { c: ["arma_fisica", "corte", "vuelo", "uso_acuatico", "lanza"], t: "Spear" },
  { c: ["arma_fisica", "latigo", "no_corte", "no_vuelo"], t: "Whip" },
  { c: ["arma_fisica", "arco_pistola", "inmunidad", "no_uso_acuatico", "no_vuelo"], t: "Archer" },
  { c: ["arma_fisica", "arco_pistola", "no_inmunidad", "no_uso_acuatico", "no_vuelo"], t: "Ranger" },
  // Combate
  { c: ["artes_marciales", "agarre_lanza", "no_nat_animal", "no_proyectil", "no_corte", "no_referencia", "no_vuelo"], t: "Throw" },
  { c: ["artes_marciales","agarre_lanza", "proyectil", "no_nat_animal", "no_corte", "no_referencia", "no_vuelo"], t: "Fighter" },
  { c: ["artes_marciales", "corte", "proyectil", "inmunidad", "no_agarre_lanza", "no_referencia", "no_vuelo"], t: "Ninja" },
  // Elementos - Fuego
  { c: ["elem_fuego", "corte", "referencia", "no_elem_agua", "no_inmunidad", "no_arma_fisica", "no_artes_marciales", "no_vuelo"], t: "Fire" },
  { c: ["elem_fuego", "cuerpo_completo", "inmunidad", "no_arma_fisica", "no_vuelo"], t: "Burning" },
  // Elementos - Hielo / Agua
  { c: ["elem_hielo", "desplazamiento", "proyectil", "inmunidad", "no_vuelo"], t: "Ice" },
  { c: ["elem_agua", "desplazamiento", "uso_acuatico", "no_vuelo"], t: "Water" },
  { c: ["elem_agua", "proyectil","no_uso_acuatico", "no_desplazamiento", "no_vuelo"], t: "Bubble" },
  // Elementos - Rayo
  { c: ["elem_rayo", "proyectil", "no_arma_fisica", "no_tecnologia_robotica", "no_magia_psiquico", "no_herramienta_trabajo", "no_vuelo"], t: "Spark" },
  { c: ["elem_rayo", "proyectil", "arma_fisica", "no_tecnologia_robotica", "no_herramienta_trabajo", "no_vuelo"], t: "Beam" },
  // Elementos - Tierra / Planta / Viento
  { c: ["elem_tierra", "caida_libre","inmunidad","referencia", "no_proyectil", "no_herramienta_trabajo", "no_arma_fisica", "no_vuelo"], t: "Stone" },
  { c: ["elem_tierra", "proyectil","inmunidad", "no_herramienta_trabajo", "no_vuelo"], t: "Sand" },
  { c: ["nat_planta", "proyectil","inmunidad", "no_vuelo"], t: "Leaf" },
  { c: ["elem_viento", "cuerpo_completo", "inmunidad", "vuelo"], t: "Tornado" },
  // Tecnología / Robot
  { c: ["tecnologia_robotica", "cuerpo_completo", "vuelo", "proyectil"], t: "UFO" },
  { c: ["tecnologia_robotica", "cuerpo_completo", "vuelo", "no_proyectil"], t: "Missile" },
  { c: ["tecnologia_robotica", "elem_fuego", "vuelo", "explosivo", "no_uso_unico", "no_arma_fisica"], t: "Jet" },
  { c: ["tecnologia_robotica", "arma_fisica", "proyectil", "vuelo", "desplazamiento"], t: "Mecha" },
  { c: ["tecnologia_robotica", "elem_rayo", "proyectil", "no_vuelo", "no_desplazamiento"], t: "Laser" },
  // Magia / Psíquico
  { c: ["magia_psiquico", "arma_fisica", "inmunidad", "desplazamiento","reflejar", "no_vuelo"], t: "Mirror" },
  { c: ["cuerpo_completo", "inmunidad", "vuelo", "no_reflejar","no_magia_psiquico", "no_nat_animal", "no_proyectil", "no_arma_fisica"], t: "Ghost" },
  { c: ["magia_psiquico", "corte", "proyectil", "no_reflejar", "no_vuelo"], t: "Magic" },
  { c: ["magia_psiquico", "elem_rayo", "proyectil", "no_reflejar", "no_vuelo"], t: "ESP" },
  // Uso Único
  { c: ["uso_unico", "explosivo", "no_vuelo"], t: "Crash" },
  { c: ["uso_unico", "arma_fisica","musica_ruido", "no_vuelo"], t: "Mike" },
  { c: ["uso_unico", "arte", "no_vuelo", "no_musica_ruido", "no_explosivo", "no_comida"], t: "Paint" },
  { c: ["uso_unico", "proyectil", "no_musica_ruido", "no_comida", "no_vuelo", "no_arma_fisica"], t: "Light" },
  { c: ["uso_unico", "musica_ruido", "no_explosivo", "no_comida", "no_proyectil", "no_vuelo"], t: "Festival" },
  // Objetos / Profesiones
  { c: ["referencia", "elem_fuego", "comida", "arma_fisica", "no_elem_agua", "no_corte", "no_cuerpo_completo", "no_vuelo"], t: "Cook" },
  { c: ["arma_fisica","uso_acuatico","sombrilla"], t: "Parasol" },
  { c: ["herramienta_trabajo", "arma_fisica", "elem_viento", "vuelo"], t: "Cleaning" },
  { c: ["herramienta_trabajo", "elem_rayo", "elem_fuego", "elem_hielo", "no_arma_fisica", "no_vuelo"], t: "Doctor" },
  { c: ["herramienta_trabajo", "elem_tierra", "desplazamiento", "inmunidad", "no_arma_fisica", "no_caida_libre", "no_vuelo"], t: "Drill" },
  { c: ["arte", "arma_fisica", "elem_agua", "no_elem_rayo","no_uso_unico", "no_inmunidad", "no_arco_pistola", "no_latigo", "no_vuelo"], t: "Artist" },
  { c: ["deporte_juego", "arma_fisica", "no_proyectil", "no_vuelo"], t: "Yo-Yo" },
  { c: ["deporte_juego", "no_arma_fisica", "no_vuelo"], t: "Circus" },
  { c: ["musica_ruido", "arma_fisica", "inmunidad", "uso_acuatico", "no_vuelo"], t: "Bell" },
  { c: ["explosivo", "proyectil", "no_uso_unico", "no_arma_fisica", "no_vuelo"], t: "Bomb" },
  // Cuerpos Completos / Movimiento
  { c: ["cuerpo_completo", "desplazamiento", "inmunidad", "no_caida_libre", "no_proyectil", "no_herramienta_trabajo", "no_vuelo"], t: "Wheel" },
  { c: ["cuerpo_completo", "no_corte","no_vuelo", "no_caida_libre", "no_inmunidad"], t: "Mini" },
  { c: ["vuelo", "corte", "proyectil", "no_arma_fisica", "no_tecnologia_robotica", "no_magia_psiquico"], t: "Wing" },
  // Otros
  { c: ["referencia", "uso_unico", "dormir", "no_arma_fisica", "no_proyectil", "no_cuerpo_completo", "no_herramienta_trabajo", "no_desplazamiento", "no_vuelo"], t: "Sleep" },
  { c: ["referencia", "artes_marciales", "no_comida", "no_cuerpo_completo", "no_arma_fisica", "no_elem_rayo", "no_uso_unico", "no_vuelo"], t: "Smash Bros" },
  { c: ["proyectil", "elem_agua", "desplazamiento", "no_uso_acuatico", "no_elem_tierra", "no_artes_marciales", "no_vuelo"], t: "Poison" },
  { c: ["arma_fisica","uso_acuatico", "no_referencia", "no_corte", "no_proyectil", "no_vuelo"], t: "Staff" },
  { c: ["inmunidad", "cuerpo_completo", "uso_acuatico", "caida_libre", "vuelo", "no_elem_tierra", "no_referencia", "no_arco_pistola", "no_corte"], t: "Metal" },
  { c: ["corte", "proyectil", "no_arma_fisica", "no_cuerpo_completo", "no_uso_acuatico", "no_inmunidad", "no_vuelo"], t: "Needle" },
];

const BASE_INFO = {
  "Animal": { e: "", d: "Garras afiladas para excavar", img: "img/animal.gif" },
  "Araña (Spider)": { e: "🕷️", d: "Envuelve en capullos de telaraña", img: "" },
  "Archer / Cupido": { e: "🏹", d: "Dispara flechas a distancia", img: "" },
  "Artist": { e: "", d: "Pinta y crea esculturas", img: "img/artist.gif" },
  "Beam": { e: "", d: "Látigo de luz disparado desde una varita", img: "img/beam.gif"},
  "Escarabajo (Beetle)": { e: "🪲", d: "Vuela y embiste con un cuerno", img: "" },
  "Campana (Bell)": { e: "🔔", d: "Usa campanas gigantes como escudo", img: "" },
  "Bomba (Bomb)": { e: "💣", d: "Lanza explosivos de forma infinita", img: "" },
  "Bubble": { e: "", d: "Lanza burbujas que atrapan cosas", img: "img/bubble.gif"},
  "Llamas (Burning)": { e: "🔥", d: "Embestida de fuego invulnerable", img: "" },
  "Circo (Circus)": { e: "🎪", d: "Acrobacias y malabares", img: "" },
  "Escoba / Limpieza (Cleaning)": { e: "🧹", d: "Barre la suciedad y enemigos", img: "" },
  "Cook": { e: "", d: "Hierve enemigos en comida", img: "img/cook.gif" },
  "Catapum (Crash)": { e: "💥", d: "Explosión masiva (1 uso)", img: "" },
  "Cupido / Arquero (Archer)": { e: "🏹", d: "Otorga alas y un arco", img: "" },
  "Cutter": { e: "", d: "Lanza un boomerang cortante", img: "img/cutter.gif" },
  "Doctor": { e: "💊", d: "Lanza píldoras y usa un portapapeles", img: "" },
  "Taladro (Drill)": { e: "🪛", d: "Excava por debajo de la tierra", img: "" },
  "Psicokinesis (ESP)": { e: "🔮", d: "Poderes psíquicos y teletransportación", img: "" },
  "Festival / Luz (Light)": { e: "🎆", d: "Ilumina zonas oscuras (1 uso)", img: "" },
  "Fighter": { e: "", d: "Técnicas de artes marciales", img: "img/fighter.gif" },
  "Fire": { e: "", d: "Aliento de fuego", img: "img/fire.gif" },
  "Ghost": { e: "", d: "Posee a los enemigos", img: "img/ghost.gif" },
  "Hammer": { e: "", d: "Mazo pesado de gran daño", img: "img/hammer.gif" },
  "Hielo (Ice)": { e: "🧊", d: "Congela enemigos con aliento helado", img: "" },
  "Reactor (Jet)": { e: "✈️", d: "Carga propulsores para volar", img: "" },
  "Hoja (Leaf)": { e: "🍃", d: "Lanza hojas y se esconde en plantas", img: "" },
  "Laser": { e: "", d: "Dispara rayos láser que rebotan", img: "img/laser.gif" },
  "Magic": { e: "", d: "Lanza palomas, cartas y trucos", img: "img/magic.gif" },
  "Meca (Mecha)": { e: "🤖", d: "Traje robótico armado", img: "" },
  "Metal": { e: "🔩", d: "Se vuelve pesado e invulnerable", img: "" },
  "Micrófono (Mike)": { e: "🎤", d: "Grita por un megáfono (1-3 usos)", img: "" },
  "Mini": { e: "", d: "Kirby se hace pequeñito", img: "img/mini.gif" },
  "Espejo (Mirror)": { e: "🪞", d: "Crea ilusiones y refleja proyectiles", img: "" },
  "Misil (Missile)": { e: "🚀", d: "Se transforma en cohete guiado", img: "" },
  "Aguja (Needle)": { e: "🦔", d: "Saca púas de todo su cuerpo", img: "" },
  "Ninja": { e: "🥷", d: "Lanza kunais y hace ninjutsu", img: "" },
  "Pintura (Paint)": { e: "🖌️", d: "Llena la pantalla de pintura (1 uso)", img: "" },
  "Parasol": { e: "☂️", d: "Protege desde arriba y flota", img: "img/parasol.gif" },
  "Spark": { e: "", d: "Carga electricidad al moverse", img: "img/spark.gif"},
  "Veneno (Poison)": { e: "🧪", d: "Dispara charcos tóxicos", img: "" },
  "Pistolero (Ranger)": { e: "🔫", d: "Dispara un par de pistolas", img: "" },
  "Arena (Sand)": { e: "🏜️", d: "Controla tormentas de arena", img: "" },
  "Sleep": { e: "", d: "Se queda dormido", img: "img/sleep.gif" },
  "Smash Bros": { e: "", d: "Set de movimientos de Smash", img: "img/smash_bros.gif" },
  "Lanza (Spear)": { e: "🔱", d: "Lanza jabalinas", img: "" },
  "Bastón (Staff)": { e: "🦯", d: "Golpea con un bastón extensible", img: "" },
  "Stone": { e: "🪨", d: "Cae en picada volviéndose invulnerable", img: "img/stone.gif" },
  "Suplex / Backdrop": { e: "💪", d: "Agarra y arroja enemigos", img: "" },
  "Sword": { e: "", d: "El arma clásica de Link", img: "img/sword.gif" },
  "Lanzamiento (Throw)": { e: "💨", d: "Arroja enemigos en línea recta", img: "" },
  "Tornado": { e: "", d: "Gira descontroladamente", img: "img/tornado.gif" },
  "UFO": { e: "🛸", d: "Vuelo infinito y rayos láser", img: "img/UFO.gif" },
  "Agua (Water)": { e: "🌊", d: "Dispara chorros de agua", img: "" },
  "Wheel": { e: "🛞", d: "Acelera por el suelo invulnerable", img: "img/wheel.gif" },
  "Látigo (Whip)": { e: "🤠", d: "Golpea y atrae objetos", img: "" },
  "Ala (Wing)": { e: "🪽", d: "Dispara plumas y vuela ágilmente", img: "" },
  "Yoyó (Yo-Yo)": { e: "🪀", d: "Lanza un yoyó", img: "" },
};